### PR TITLE
Adding the possibility to include the local files (not only compass libs like now)

### PR DESCRIPTION
**Pull request by vshjxyz**
Adding the functionality to @include other scss locally, so now if we have a situation like:

├── _ie.scss
├── print.scss
├── screen.scss
└── style.scss

if we do @import "ie"; inside the style.scss, it works

### CODE REVIEW

**Comment by vshjxyz** [comment]
Hello, can you please push the new version (let's say 0.1.4) with this merge to PyPi?  Just to be sure that now it behaves also in this way

**Comment by vshjxyz** [comment]
Any news on the Pypi update?

**Comment by vbabiy** [comment]
Yes I will do this today. Sorry it fell through the cracks.

**Comment by vbabiy** [comment]
http://pypi.python.org/pypi/django-pipeline-compass/0.1.4

Sorry for the delay.

**Pull request merged**
